### PR TITLE
Fixed Mayhem Integration Again

### PR DESCRIPTION
**Pull request by Gediminas19**
@xansec, I made a few minor changes to get mayhem integration working again:

- Rust toolchain version (in `rust-toolchain`) now matches tikv/tikv master. It was also necessary, since some of the newly added code relies on the newer version.
- For the `futures` crate in `components/tikv_util/Cargo.toml`, the `thread-pool` feature is necessary for `tikv` to build successfully. This seems to be an issue with the tikv/tikv master branch.

[This github action run](https://github.com/Gediminas19/tikv/runs/7018126424?check_suite_focus=true) on my fork of the repo shows it working.

### CODE REVIEW

**Comment by Gediminas19** [comment]
@rizaziz Can you explain what happened?

**Comment by Gediminas19** [comment]
I know force pushing is not ideal, but the history of the `mayhemheroes/tikv:master` branch seems to be really screwed up (@rizaziz seems to have put my commits from 3 weeks ago onto a branch called `old_history`, them manually redid them on `master`). I have just pulled from `tikv/tikv:master`, made the changes again, and force pushed. All the force pushing was done on my own fork at `Gediminas19/tikv:mayhem` branch, so it should not affect this repo I think.

**Comment by xansec** [comment]
Hi Ethan, I sincerely apologize for this. It appears that some of our backend automation unintentionally closed your PR when doing some branch pruning. We are squashing commits from upstream merges and heroes changes into a single commit for PR purposes (we want to be able to see all changes in a single commit), but this resulted in a conflict on this particular repo when the unsquashed branch was pruned. As far as I know, no other repo should be affected. 

Unfortunately, it does look like the PR now contains a huge amount of changes (likely due to the difference between your mayhem branch and the recently sync'd with upstream master branch). Can you check that your mayhem branch is up to date with upstream's master? If not, please sync your mayhem branch with upstream master. I think the only changes you actually made are here:
https://github.com/Gediminas19/tikv/commit/ad080eb3ddf797b8ac20c96ec86426d9812439c7
So if I am correct then afterwards this PR should only contain changes for the two files referenced in the above commit.

**Comment by Gediminas19** [comment]
@xansec on commit [62db5db](https://github.com/mayhemheroes/tikv/pull/3/commits/62db5db204abae02313ab9280d6c6e2b53fc36b5) I already merged `tikv/tikv:master` into my `gediminas19/tikv:mayhem` branch. There have been 3 more commits to master since then, which I just merged in as well.

And yes, [ad080eb](https://github.com/Gediminas19/tikv/commit/ad080eb3ddf797b8ac20c96ec86426d9812439c7) contains the only actual changes I made.

**Comment by xansec** [comment]
For whatever reason this PR still has a lot of changes although it should be sync'd with upstream. I'm not entirely sure what's going on here, but I pushed your changes to the master branch myself and it seems to be successful:
https://github.com/mayhemheroes/tikv/runs/7054504699?check_suite_focus=true
Anyways, this is a result of processes on our end and shouldn't be your responsibility. The integration is successful. I'll close this PR for now.

**Pull request closed without merging**
